apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd

    spec:
      initContainers:
        - name: init-config-folder
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /mnt/config/sabnzbd & \
              ls -lah /mnt/config & \
              ls -lah /mnt/config/*
          volumeMounts:
            - name: config
              mountPath: /mnt/config
      containers:
      - name: sabnzbd
        # https://hub.docker.com/r/binhex/arch-sabnzbdvpn/tags
        image: binhex/arch-sabnzbdvpn:4.5.5-1-01
        resources:
          requests:
            memory: "6Gi"
            cpu: "6000m"
          limits:
            memory: "16Gi"
            cpu: "10000m"
        securityContext:
          # runAsNonRoot: true
          # runAsUser: 1000
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 8080
        - containerPort: 8090
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        - name: VPN_ENABLED
          value: "yes"
        - name: VPN_USER
          valueFrom:
            secretKeyRef:
              name: sabnzbd-secrets
              key: PIA_USER
        - name: VPN_PASS
          valueFrom:
            secretKeyRef:
              name: sabnzbd-secrets
              key: PIA_PASS
        - name: VPN_PROV
          value: "pia"
        - name: VPN_CLIENT
          value: "openvpn"
        - name: ENABLE_PRIVOXY
          value: "no"
        - name: STRICT_PORT_FORWARD
          value: "no"
        - name: LAN_NETWORK
          value: "10.0.0.0/8"
        - name: NAME_SERVERS
          value: "1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4"
        - name: DEBUG
          value: "false"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: sabnzbd
        - name: downloads
          mountPath: /config/Downloads
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: sabnzbd-downloads-sabnzbd-pvc
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config-pvc