apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy

    spec:
      containers:
      - name: grocy
        image: linuxserver/grocy:4.5.0
        
        securityContext:
          runAsNonRoot: false
          # runAsUser: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "4000m"
        ports:
          - containerPort: 80
        env:
        volumeMounts:
        - name: grocy-data
          mountPath: /config
        # livenessProbe:
        #   httpGet:
        #     path: /api/healthz
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
      volumes:
      - name: grocy-data
        hostPath:
          path: /lxc-configs/grocy-config # This path contains the same files on all nodes 
          type: DirectoryOrCreate