apiVersion: apps/v1
kind: Deployment
metadata:
  name: filerun-mfox
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filerun-mfox
  template:
    metadata:
      labels:
        app: filerun-mfox
    spec:
      containers:
      - name: filerun-mfox
        image: filerun/filerun:8.4
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "6Gi"
            cpu: "6000m"
        ports:
          - containerPort: 80
        env:
          - name: FR_DB_HOST
            valueFrom:
              secretKeyRef:
                name: filerun-mfox-secrets
                key: FR_DB_HOST
          - name: FR_DB_PORT
            valueFrom:
              secretKeyRef:
                name: filerun-mfox-secrets
                key: FR_DB_PORT
          - name: FR_DB_NAME
            valueFrom:
              secretKeyRef:
                name: filerun-mfox-secrets
                key: FR_DB_NAME
          - name: FR_DB_USER
            valueFrom:
              secretKeyRef:
                name: filerun-mfox-secrets
                key: FR_DB_USER
          - name: FR_DB_PASS
            valueFrom:
              secretKeyRef:
                name: filerun-mfox-secrets
                key: FR_DB_PASS
          - name: APACHE_RUN_USER
            value: "www-data"
          - name: APACHE_RUN_USER_ID
            value: "33"
          - name: APACHE_RUN_GROUP
            value: "www-data"
          - name: APACHE_RUN_GROUP_ID
            value: "33"
        volumeMounts:
          - name: user-files
            mountPath: /user-files
          - name: filerun-html
            mountPath: /var/www/html
      volumes:
      - name: user-files
        persistentVolumeClaim:
          claimName: filerun-mfox-files-pvc
      - name: filerun-html
        hostPath:
          path: /mnt/kubernetes-data/filerun-mfox/html # This path contains the same files on all nodes 
          type: DirectoryOrCreate
