apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-forwardauth
  namespace: web
spec:
  forwardAuth:
    address: http://oauth2-proxy.web.svc.cluster.local/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Access-Token
      - X-Auth-Request-Groups
